export * from './NavBar';
export * from './NavBarMobile';
export * from './Header';
export * from './TurneraSimple'
export * from './S4Card1';
export * from './S4Card2';
export * from './S4Card3';
export * from './TextUpComponent';
export * from './TurneraMensual';
export * from './TurneraSimple';
export * from './Whatsapp';
